### PR TITLE
Check links using GH Action

### PR DESCRIPTION
**Pull request by dholbach**
Breaking this out of https://github.com/weaveworks/ignite/pull/565

### CODE REVIEW

**Comment by luxas** [comment]
@dholbach this should be ready to rebase and merge now

**Comment by luxas** [comment]
@dholbach if you have time to get back to this (rebase & make it green) I'll help you get it merged ASAP :smile:

**Comment by dholbach** [comment]
Unfortunately it's not so easy. The `ignite` docs are essentially a link-farm and we get rate-limited from e.g. Github after checking all these links.

**Comment by dholbach** [comment]
I need help fixing the remaining bit:

```
 site/api/ignite_v1alpha1/index.html
	ERROR	https://github.com/weaveworks/ignite/tree/master/pkg/apis/ignite/v1alpha1/types.go?s=8278:8315#L226
		Too Many Requests (HTTP error 429)
site/api/ignite_v1alpha2/index.html
	ERROR	https://github.com/weaveworks/ignite/tree/master/pkg/apis/ignite/v1alpha2/types.go?s=7227:7371#L189
		Too Many Requests (HTTP error 429)
```

It's too many requests. Github is not happy.

cc @luxas

**Comment by luxas** [comment]
Hmm, I'm not sure what to do about it :(

**Comment by dholbach** [comment]
Looks like it is passing this time. :crossed_fingers:

**Pull request merged**
