### PR TITLE
Upgrade firecracker to v0.22.4

### PR DESCRIPTION
**Pull request by gaby**
This PR takes care of upgrading firecracker from v0.22.1 to v0.22.4

### Review of firecracker changes:

v0.22.2
- Fixed inconsistency in YAML file InstanceInfo definition

v0.22.3
- Fixed off-by-one error in virtio-block descriptor address validation.

v0.22.4
- Fixed the reported used bytes for any virtio-block request.
- Fixed all virtio-block read/write operations to valid guest addresses
with buffer length of 0 to result in no-op.

### CODE REVIEW

**Comment by gaby** [comment]
Build is failing because firecracker updated their release path. Each release now provides a `.tgz` file

**Comment by darkowlzz** [comment]
Thanks for updating the firecracker version. The changes look good to me. Can you also update the installation docs to reflect this change? https://github.com/weaveworks/ignite/blob/master/docs/installation.md#ignite-cli - firecracker version in the output.
Also, maybe squash the commits if possible :slightly_smiling_face:

**Comment by gaby** [comment]
@darkowlzz Done, I'm using Github Desktop app and it doesn't have an option for squashing commits. I know there's an option to do it here via the PR but i don't see it on this repo.

**Comment by darkowlzz** [comment]
> @darkowlzz Done, I'm using Github Desktop app and it doesn't have an option for squashing commits. I know there's an option to do it here via the PR but i don't see it on this repo.

That's okay. np.

**Comment by stealthybox** [comment]
Thank you for all of this incredible work.
This is significant maintenance effort to track all the dependencies -- we really appreciate it.

**Pull request merged**
