### PR TITLE
Bump default kernel to 5.4.102

### PR DESCRIPTION
**Pull request by gaby**
Now that new kernel images are being built, the default kernel used by Ignite needs to be updated.

There's also several tickets regarding bumping this to kernel 5.4.x, thoughts?

See #768 #623

### CODE REVIEW

**Comment by gaby** [comment]
It seems like the tests also need to be updated. I will take a look again tonight.

**Comment by gaby** [comment]
Seems like the test needs to be re-run? @stealthybox

**Comment by stealthybox** [comment]
@gaby -- after talking this through /w @darkowlzz we think your suggestion to update the default to `5.4.102` is a good one.
Would you like to update this patch? :)

**Comment by gaby** [comment]
@stealthybox I just pushed the requested change. Default kernel is now 5.4.102

**Pull request merged**
