### PR TITLE
Add next-action for better developer-workflow

### PR DESCRIPTION
**Pull request by alexellis**
Adds a next-action of using Ignite after installing it.

Signed-off-by: Alex Ellis <alexellis2@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for merging!

@luxas should I need to install KVM packages on Ubuntu for instance? If so, I would like to add a link to the requirements docs page i.e. See also: KVM on Ubuntu / KVM on CentOS / KVM on Fedora.

**Comment by luxas** [comment]
> should I need to install KVM packages on Ubuntu for instance

No, just KVM support in the kernel/processor is enough.
Is the current merging in https://github.com/weaveworks/ignite/blob/master/docs/installation.md#system-requirements ok?

**Comment by alexellis** [comment]
Looks good. I wonder if you can install `kvm-ok` without installing a load of other packages for libvirt?

```
# kvm-ok

Supported...
```

**Comment by luxas** [comment]
I just checked that yes, you can get it via a `apt-get install cpu-checker`, without libvirt deps. I'll create an issue

**Pull request merged**
