### PR TITLE
first circleci test

### PR DESCRIPTION
**Pull request by luxas**
I think that something like this may do it, but I've never used Circle before so ¯\_(ツ)_/¯

Partly fixes: #71

### CODE REVIEW

**Comment by luxas** [comment]
The build passes :tada:!
That's enough for today. Tomorrow I'll look into getting the tests running in CI too

**Comment by aojea** [comment]
@luxas don´t you implement a workflow?
let me know if you need help with this, I have some experience with circleCI

**Comment by aojea** [comment]
scratch it, I see that this is WIP https://github.com/weaveworks/ignite/pull/280/files, sorry for the noise 😅

**Comment by luxas** [comment]
I'll fix up some stuff in #280, but I'd definitely appreciate help with the rest that I won't fix in #280 (e.g. import-boss stuff #260 and/or golang-ci-lint). Thanks :clap:!

**Pull request merged**
