### PR TITLE
add forward rules for the bridge device

### LINKED ISSUE #401: Networking: no route to host
Ingress and outgress networking doesnt work when spinning up vms from example, see screenshot.
I can attach to VM and do anything that doesnt involve 

Host:
```
> ip addr show cni0                                                                                                                                                                                                                         Thu 05 Sep 2019 18:19:44 IST
51: cni0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 16:94:03:be:10:25 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::1494:3ff:febe:1025/64 scope link 
       valid_lft forever preferred_lft forever
```

VM:
```
root@localhost:~# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether ea:9a:88:b7:ad:bf brd ff:ff:ff:ff:ff:ff
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 8a:ef:19:a1:97:55 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.6/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::88ef:19ff:fea1:9755/64 scope link 
       valid_lft forever preferred_lft forever
```

![image](https://user-images.githubusercontent.com/18282288/64363980-da769b80-d009-11e9-9f16-ac147995301d.png)

### LINKED ISSUE #418: When using containerd + CNI network, the VM could not ping the Internet IPs
When using CNI network, the VM could not ping the Internet IPs.

This is because there is no forward setting in iptables to handle traffic atm.
We should implement this inside `pkg/network/cni`.

### PR DESCRIPTION
**Pull request by chanwit**
This PR allows forwarding from and to the CNI bridge device. It's to support IP masquerade enabled by CNI bridge config.

To test:
  1. `ignite run` a VM
  1. `ignite exec -- ping 8.8.8.8`

Fixes #401 
Fixes #418

### CODE REVIEW

**Comment by chanwit** [comment]
Refer to the implementation found on the `containernetworking/plugins`
```
*filter
:FORWARD ACCEPT [0:0]
:CNI-ADMIN-cni0 - [0:0]
:CNI-FORWARD-cni0 - [0:0]
-A FORWARD -i cni0 ! -o cni0 -m comment --comment "CNI interface cni0 administrator overrides" -j CNI-ADMIN-cni0
-A FORWARD -m comment --comment "CNI interface cni0 private rules" -j CNI-FORWARD-cni0
-A CNI-FORWARD-cni0 -i cni0 ! -o cni0 -j ACCEPT
-A CNI-FORWARD-cni0 -i cni0 -o cni0 -j ACCEPT
-A CNI-FORWARD-cni0 -o cni0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
```

https://github.com/containernetworking/plugins/pull/75#issuecomment-333249070

**Comment by chanwit** [comment]
reworked to remove the DNS related commit.
kindly ping @stealthybox

**Comment by stealthybox** [comment]
I'm excited about this because it works well for me.
Should we add the `CNI-FORWARD` and `CNI-ADMIN` chains?

We haven't heard of any other reports of a working configuration beyond @luxas's devel recollection, so I'm thinking this an approach to get this working -- at least for a larger user-base.

There's some quick notes in that thread you linked about distro-specific iptables filter rules.

I tried getting the `firewall` plugin working before, but now I'm more familiar with the problem.
Have you tried that yet? If it works, it's best if we don't have to maintain these rules.

**Comment by chanwit** [comment]
AFAIC, this set of rules are quite stable already. I mean it's a normal pattern found in many network implementation.

Creating `CNI-FORWARD` would be colliding with other CNI implementations. If we'd like to do so, we could name it `IGNITE-FORWARD`.

But I don't think we need the `ADMIN` chain. Or at least I don't have an idea why we need it?

WDYT?

**Comment by stealthybox** [comment]
> Creating CNI-FORWARD would be colliding with other CNI implementations

Seems the canonical name is `CNI-FORWARD-bridgeName` / `CNI-ADMIN-bridgeName`
Right now, our bridge is named `cni0`, but that would change the names of the chains as well when we move to `ignite0` with the new subnet.

I do think we should add comments to all of our rules if we're creating them: https://github.com/stealthybox/ignite/commit/9c10c3105b19055e420eccf3529a46ec3dbcd822

If the `firewall` plugin can do this automatically -- it's more true to CNI and less magic in our config.
We should try it out in a separate PR since it should be a simple change.

**Comment by chanwit** [comment]
Closing this in favor of #442

**Pull request closed without merging**
