### PR TITLE
Add a k3s sample image

### PR DESCRIPTION
**Pull request by EmeraldShift**
This change adds an image for k3s, a lightweight Kubernetes distribution, as per #329.

A few notes:
* The `rancher/k3s` image seems to be too minimal to function correctly—for example, it wouldn't mount `/proc`, etc. Thus, this image is based on Ubuntu 20.04, with k3s installed via the provided Rancher script
* Docker can't properly handle [tags with a `+` symbol in them](https://github.com/moby/moby/issues/16304), so the version of k3s used for this image is the highest version before `+` was introduced into the release tags, i.e. v1.0.1.
* The image was tested by deploying a [hello-kubernetes](https://github.com/paulbouwer/hello-kubernetes) manifest. The service was reachable from the host (outside the VM) via the external IP leased to the `hello-kubernetes` Service.

### CODE REVIEW

**Comment by EmeraldShift** [comment]
@stealthybox I think this one's ready for review.
Looking through the details of the build failure, I'm not sure how they're related to these changes, but instead they seem like transient failures of some sort. I'm not sure how to get them to pass. Any ideas?

**Review by darkowlzz — COMMENTED** [review]
I tried the image myself and it works as expected.
Had to set 2GB memory for the VM, else k3s fails with out of memory error. The default 512MB of memory is not enough. We can document it better, similar to the README in images/kubeadm/README.md.
We can also add docs for multi-node HA setup separately, similar to kubeadm, in the future.
Thanks for working on this.

**Comment by darkowlzz** [comment]
We don't run the OS image builds in the regular CI, so the build failure is unrelated. Don't need to worry about it 🙂

**Comment by EmeraldShift** [comment]
@darkowlzz Thank you for the feedback! I've patched the Makefile with the changes you mentioned, and added a simple README.

**Comment by stealthybox** [comment]
LGTM -- thanks for fixing the tag problem

**Review by darkowlzz — APPROVED** [review]
LGTM! Thanks.

**Pull request merged**
