### PR TITLE
Upgrade kernel versions

### PR DESCRIPTION
**Pull request by gaby**
* Upgrade from kernel 4.14.182 to 4.14.223
* Upgrade from kernel 4.19.125 to 4.19.178
* Upgrade from kernel 5.4.43 to 5.4.102

Source: [https://www.kernel.org/](https://www.kernel.org/)

* Note: Versions as of 2021-03-04

* Future proposal: Instead of pinned patch versions, determine the latest patch version via CI. Add a scheduled github workflow that downloads the latest patch versions on a weekly basis.

### CODE REVIEW

**Comment by gaby** [comment]
Build failed: 

```
time="2021-03-05T06:40:50Z" level=info msg="Waiting for the ssh daemon within the VM to start..."05:30
    TestConcurrentVMCreation: zconcurrent_vm_test.go:48: assertion failed: error is not nil: exit status 1: error waiting for the command to finish05:30
    TestConcurrentVMCreation: zconcurrent_vm_test.go:48: assertion failed: error is not nil: exit status 1: error waiting for the command to finish05:30
    TestConcurrentVMCreation: zconcurrent_vm_test.go:50: assertion failed: error is not nil: exit status 1: cmd: 05:30
        "/home/semaphore/ignite/bin/ignite rm -f e2e-test-concurrent-vm-create-1 e2e-test-concurrent-vm-create-2 e2e-test-concurrent-vm-create-3 e2e-test-concurrent-vm-create-4"05:30
        time="2021-03-05T06:40:57Z" level=fatal msg="can't find VM: no ID/name matches for \"e2e-test-concurrent-vm-create-4\""05:30
        05:30
    TestConcurrentVMCreation: zconcurrent_vm_test.go:50: failed to run "/home/semaphore/ignite/bin/ignite rm -f e2e-test-concurrent-vm-create-1 e2e-test-concurrent-vm-create-2 e2e-test-concurrent-vm-create-3 e2e-test-concurrent-vm-create-4": exit status 105:30
--- FAIL: TestConcurrentVMCreation (9.00s)05:30
FAIL05:30
FAIL	github.com/weaveworks/ignite/e2e	327.120s05:30
FAIL05:30
Makefile:281: recipe for target 'e2e-nobuild' failed05:30
make: *** [e2e-nobuild] Error 1
```

**Comment by gaby** [comment]
Should be good now :-)

**Comment by gaby** [comment]
I have no idea why this is failing now, if it wasn't before?

**Comment by darkowlzz** [comment]
> I have no idea why this is failing now, if it wasn't before?

Don't worry about that. There's some test flake we are aware of. Reran the job and it's green now :slightly_smiling_face: 
Thanks for the patch.

**Comment by gaby** [comment]
These kernels are already 1 patch outdated. I will update the PR later today.

**Comment by stealthybox** [comment]
> These kernels are already 1 patch outdated. I will update the PR later today.

We can't be perpetually up to date in a way that will scale with manual action -- We're inclined to merge this now.

How often would you like to see the newest patches pushed if we do this in an automated fashion?
Weekly like you mentioned in the patch description?
Would that be useful for you (or others)?

We did start some pre-requisite work scripting against upstream kernel.org tags and could use the release machinery to automate this weekly.

**Comment by stealthybox** [comment]
Merged -- feel free to continue discussion here
We also meet on Zoom every Monday (US morning timezone)

**Comment by gaby** [comment]
@stealthybox Makes sense, weekly updates of kernel versions would be ideal.

**Comment by gaby** [comment]
@stealthybox It seems none of the new images got released. Are the github actions for new images only running when a new tag is created?

**Pull request merged**
