### PR TITLE
Update OS and kernel versions

### PR DESCRIPTION
**Pull request by luxas**
@darkowlzz @stealthybox 

```
make -C images build-all
make -C images/kernel upgrade
make -C images/kernel build
```

### CODE REVIEW

**Comment by casibbald** [comment]
Any chance we can get a 5.6 kernel on Ubuntu 20.04?

**Comment by luxas** [comment]
> Any chance we can get a 5.6 kernel on Ubuntu 20.04?

Should be (pretty easily) doable.

**Comment by stealthybox** [comment]
@casibbald that's a very recent kernel version -- I'm curious what your use-case is :)

My concern if we were to publish latest kernels would be not being able to update them frequently without CI running on cron.

I think we're happy to publish the newer kernel build even if it's just a one-time/infrequent thing though.

**Comment by stealthybox** [comment]
Also noting I was wrong about the kubernetes version
Latest is `1.18.3`

**Pull request merged**
